#!/usr/bin/env bash

helm uninstall kvie

build_server(){
  docker build ./server -t server:latest
  minikube image rm server:latest
  minikube image load server:latest
}

build_webapp(){
  docker build . -t webapp:latest
  minikube image rm webapp:latest
  minikube image load webapp:latest
}

if [[ "$1" == "-s" ]]; then 
 build_server
elif [[ "$1" == "-w" ]]; then 
  build_webapp
else 
  build_webapp
  build_server
fi 

helm install kvie ./kvie-chart 
