apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range $key, $value := .Values.frontend.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}

